version: "3.9"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    environment:
      JENKINS_URL: ${JENKINS_URL}
      USER_1: ${USER_1}
      USER_1_PASSWORD: ${USER_1_PASSWORD}
      USER_2: ${USER_2}
      USER_2_PASSWORD: ${USER_2_PASSWORD}
    image: jenkins-server:latest
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - ./config/casc_configs:/var/jenkins_home/casc_configs
      - ${SSH_DIR}/${SSH_KEY}:/var/jenkins_home/.ssh/id:ro