credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          description: "Jenkins ssh key for Git"
          id: "jenkins-git-ssh"
          privateKeySource:
            directEntry:
              privateKey: "${file:/var/jenkins_home/.ssh/id}"
          scope: GLOBAL
          username: "jenkins_sa"
          usernameSecret: true