jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "${USER_1}"
        password: "${USER_1_PASSWORD}"
      - id: "${USER_2}"
        password: "${USER_2_PASSWORD}"
unclassified:
  location:
    url: "${JENKINS_URL}"