jobs:
  - script: >
      job('Job-of-Jobs') {
        scm {
          git {
            remote {
              credentials('jenkins-git-ssh')
              url('git@github.com:mattnspa/jenkinsJobs.git')
            }
            branch('main')
          }
        }
        steps {
          dsl {
            external("**/*.groovy")
          }
        }
      }